### THIS FILE IS AUTOGENERATED. DO NOT EDIT THIS FILE DIRECTLY ###
from . import analysis_configuration_pb2_grpc
from . import analysis_configuration_pb2
from .analysis_configuration_pb2 import *
from .analysis_configuration_pb2_grpc import *
from minknow.rpc._support import MessageWrapper, ArgumentError

__all__ = [
    "AnalysisConfigurationService",
    "EventDetection",
    "ReadDetectionParams",
    "ReadClassificationParams",
    "HistogramDocument",
    "BasecallerParams",
    "ChannelStates",
    "GetAnalysisConfigurationRequest",
    "AnalysisConfiguration",
    "SetAnalysisConfigurationResponse",
    "SetAnalysisEnabledStateRequest",
    "SetAnalysisEnabledStateResponse",
]

class AnalysisConfigurationService(object):
    def __init__(self, channel):
        self._stub = AnalysisConfigurationServiceStub(channel)
        self._pb = analysis_configuration_pb2

    def get_analysis_configuration(self, message=None, **kwargs):
        """
        Get the analysis configuration

        :rtype: AnalysisConfiguration
        """
        if message is not None:
            return MessageWrapper(self._stub.get_analysis_configuration(message), unwraps=[])

        unused_args = set(kwargs.keys())

        message = GetAnalysisConfigurationRequest()

        if len(unused_args) > 0:
            raise ArgumentError("get_analysis_configuration got unexpected keyword arguments '{}'".format("', '".join(unused_args)))
        return MessageWrapper(self._stub.get_analysis_configuration(message), unwraps=[])

    def set_analysis_configuration(self, message=None, **kwargs):
        """
        Sets the analysis configuration

        This sets the whole configuration as-is, so you have to specify the whole analysis configuration as any fields
        there previously will be overwritten. To preserve the current analysis configuration, use a get-modify-set
        approach. Use get_analysis_configuration to retrieve the current config and modify the fields on that copy.
        Then use this call to set the modified version.

        The AnalysisConfiguration message is intended to be used to convert easily from protobuf to json and back again.
        To convert from json to a protobuf message (assuming 'analysis_conf_json' holds the json data:

        >>> import minknow
        >>> from google.protobuf import json_format
        >>>
        >>> analysis_conf_pb = minknow.rpc.analysis_configuration_service.AnalysisConfiguration()
        >>> json_format.Parse(json.dumps(analysis_conf_json), analysis_conf_pb)

        To convert from a protobuf message to json:

        >>> json_data = json_format.MessageToJson(analysis_conf_resp, preserving_proto_field_name=True, including_default_value_fields=True)

        'preserving_proto_field_name' is needed because json_format will try convert keys to json-standard(?) format, like converting
        my_key to myKey, and the key names as seen in the protobuf file are important to minknow

        'including_default_value_fields' is needed because in proto3, primitive values that are default initialised (like a uint32 with value 0) 
        will not be sent on the wire, so the value wouldn't appear when converting to json. In practice, most values are wrapper types and this
        field won't have an affect in wrapper types, but it does affect enum types as the default initailised value is the 0th enum.

        :param event_detection:
        :param read_detection:
        :param read_detection_alt:
        :param read_classification:
        :param histograms:
        :param basecaller:
        :param channel_states:
        :rtype: SetAnalysisConfigurationResponse
        """
        if message is not None:
            return MessageWrapper(self._stub.set_analysis_configuration(message), unwraps=[])

        unused_args = set(kwargs.keys())

        message = AnalysisConfiguration()

        if 'event_detection' in kwargs:
            unused_args.remove('event_detection')
            message.event_detection.CopyFrom(kwargs['event_detection'])

        if 'read_detection' in kwargs:
            unused_args.remove('read_detection')
            message.read_detection.CopyFrom(kwargs['read_detection'])

        if 'read_detection_alt' in kwargs:
            unused_args.remove('read_detection_alt')
            message.read_detection_alt.CopyFrom(kwargs['read_detection_alt'])

        if 'read_classification' in kwargs:
            unused_args.remove('read_classification')
            message.read_classification.CopyFrom(kwargs['read_classification'])

        if 'histograms' in kwargs:
            unused_args.remove('histograms')
            for key, value in kwargs['histograms'].items():
                message.histograms[key].CopyFrom(value)

        if 'basecaller' in kwargs:
            unused_args.remove('basecaller')
            message.basecaller.CopyFrom(kwargs['basecaller'])

        if 'channel_states' in kwargs:
            unused_args.remove('channel_states')
            for key, value in kwargs['channel_states'].items():
                message.channel_states[key].CopyFrom(value)

        if len(unused_args) > 0:
            raise ArgumentError("set_analysis_configuration got unexpected keyword arguments '{}'".format("', '".join(unused_args)))
        return MessageWrapper(self._stub.set_analysis_configuration(message), unwraps=[])

    def set_analysis_enabled_state(self, message=None, **kwargs):
        """
        Enable or disable analysis entirely

        :param enable: (required)
        :rtype: SetAnalysisEnabledStateResponse
        """
        if message is not None:
            return MessageWrapper(self._stub.set_analysis_enabled_state(message), unwraps=[])

        unused_args = set(kwargs.keys())

        message = SetAnalysisEnabledStateRequest()

        if 'enable' in kwargs:
            unused_args.remove('enable')
            message.enable = kwargs['enable']
        else:
            raise ArgumentError("set_analysis_enabled_state requires a 'enable' argument")

        if len(unused_args) > 0:
            raise ArgumentError("set_analysis_enabled_state got unexpected keyword arguments '{}'".format("', '".join(unused_args)))
        return MessageWrapper(self._stub.set_analysis_enabled_state(message), unwraps=[])


