language: python
python:
- '3.6'
install:
- pip install -r dev-requirements.txt
- pip install .
script:
- pytest test/test_*.py
deploy:
  provider: pypi
  user: __token__
  password:
    secure: azLu4c7qF8G65qdpKNjyJK2K+AtCCHeQbbeVwyc5eltg12gqEcChLMePoAeSuBUhWZn63Xz3OEhJ7bCW0mDINqhYSE60LLfwajvQAJfVj+V9tUUr58/IfXVphAFPbyjSgsU0nQirf7iKsj5KfhrkiC/ZXMRz7VGiOiCgWG56exFOjhFjE/qCcXZvR5K4v740JQkMyf/BHQJhCdhl/chtd3dkZ/unLwWNOSK/OyFLH6FUISc5NlBUuzODyG4ItTl5NGQ+1xTIb4EytknZYoduM1Makyy0zdXBABSzhzIkBhYOtgu9ah7fUa61WY2KDMdjOK9meed8jLETOV9H/dxtCpkVejXv8fJ55V/fyj3WBuADXHbZHXLIn0+ftcBk/73O1pFgSnhRdUTInEqBEYvdNaOpvUqTIZFLBSuiU5V8uZoxqTepasx4hmdO0xmsAUaXvdPh/nXGyy33umFCGVXnJwrD/uD3x3oob9ovGcwFt1lsQi9t7IJHaGeNYKyhQjVhswy6BzuqAtJfKiQ6X+4p0meG7HYKH4c1vZtgkS3OgWM9oPjR9EiYs6N3+auKP3750k1me6vqKwbAYYTJkbKhHI6jlhGGlv8NpnaZGSrh98XhXvvXWayEHXwlHWGCGC5HPbJf/vnqBMjQQUwqfnnDNcJ5EJv1WlBs0D7GfQ2tJ28=
